name       : ruby-optimist
version    : 3.0.1
release    : 3
source     :
    - https://rubygems.org/downloads/optimist-3.0.1.gem : 336b753676d6117cad9301fac7e91dab4228f747d4e7179891ad3a163c64e2ed
license    : MIT
component  : programming.ruby
summary    : Optimist is a commandline option parser for Ruby that just gets out of your way.
description: |
    Optimist is a commandline option parser for Ruby that just gets out of your way.
builddeps  :
    - pkgconfig(ruby-2.7)
rundeps    :
    - ruby
replaces   :
    - ruby-trollop
install    : |
    %gem_install
    rm -rf $installdir/$geminstalldir/{build_info,doc,extensions}
    rm -rf $installdir/$geminstalldir/gems/optimist-$version/{.gitignore,History.txt,README.md}
