name       : ruby-optimist
version    : 3.0.1
release    : 5
source     :
    - https://rubygems.org/downloads/optimist-3.0.1.gem : 336b753676d6117cad9301fac7e91dab4228f747d4e7179891ad3a163c64e2ed
homepage   : https://rubygems.org/gems/optimist
license    : MIT
component  : programming.ruby
summary    : Optimist is a commandline option parser for Ruby that just gets out of your way
description: |
    Optimist is a commandline option parser for Ruby that just gets out of your way. One line of code per option is all you need to write. For that, you get a nice automatically-generated help page, robust option parsing, command subcompletion, and sensible defaults for everything you don't specify.
builddeps  :
    - pkgconfig(ruby-3.1)
rundeps    :
    - ruby
replaces   :
    - ruby-trollop
install    : |
    %gem_install
    rm -rf $installdir/$geminstalldir/{build_info,doc,extensions}
    rm -rf $installdir/$geminstalldir/gems/optimist-$version/{.gitignore,History.txt,README.md}
