name       : ruby-optimist
version    : 3.0
release    : 2
source     :
    - https://rubygems.org/downloads/optimist-3.0.0.gem : 9248b63be64ee1516f2e1a1d98d8528571eb2a48399e19188db1d865c7cd5d16
license    : MIT
component  : programming.ruby
summary    : Optimist is a commandline option parser for Ruby that just gets out of your way.
description: |
    Optimist is a commandline option parser for Ruby that just gets out of your way.
builddeps  :
    - pkgconfig(ruby-2.6)
rundeps    :
    - ruby
install    : |
    %gem_install

    # Removing empty folders and unnecessary files.
    rm -rf $installdir/usr/lib64/ruby/gems/2.6.0/{build_info,doc,extensions}
    rm -rf $installdir/usr/lib64/ruby/gems/2.6.0/gems/optimist-3.0.0/{.gitignore,History.txt,README.md}
